### ISSUE TITLE
system requirement and user guide

### ISSUE THREAD

**Issue by junqi108** [PlantSimulationLab/Helios#1]
Hi Helios team: 
What is computer specification that you are currently using? I would like to download and test the software, but I feel my current laptop is not suitable for this as it is a windows system. 
note on the website:
Currently, Helios is only compatible with Mac and Linux platforms. Some plug-ins require an NVIDIA graphics processing unit (GPU), such as the radiation model and LiDAR plug-ins.

By the way, is there a software user guide? 
thanks very much in advance. 
Cheers. 
Junqi

**Comment by rarygit** [comment]
You could try installing Windows 10 "Windows Subsystem for Linux".
