### ISSUE TITLE
[bug]function loadPLY

### ISSUE THREAD

**Issue by Pepe-oss** [PlantSimulationLab/Helios#29]
Hi,
    I using `context.loadPLY()` function to import .ply mesh file. After visualization, I found that the mesh should rotate 90 degrees around the x-axis. I tried `Helios/samples/radiation_StanfordBunny` that its mesh looks like normal in using `vis.plotInteractive();`. So I open PLY/StanfordBunny.ply  in matlab, and I found this StanfordBunny mesh actually rotate 90 degrees around the x-axis when It looks normal after reading. So maybe I think this function may have some problems in reading ply with the coordinate axis. 

Thanks!

**Comment by bnbailey-psl** [comment]
Helios assumes that the up-axis for PLY files is Y-up (which is most common in computer graphics), so it automatically rotates it to be Z-up (which is what is used in Helios). There is an optional argument to the loadPLY() function that allows you to specify a custom rotation for the model. The loadOBJ() function allow you to specify the up-axis directly as an argument, which is maybe more intuitive than having to specify a rotation angle. I can easily add this feature to loadPLY() to make it more intuitive.

**Comment by Pepe-oss** [comment]
> 

Thanks!
